default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: punchlist_dev

test:
  <<: *default
  database: punchlist_test

production:
  <<: *default
  database: punchlist_prod
  username: punchlist
  password: <%= ENV['PUNCHLIST_DATABASE_PASSWORD'] %>
